### ISSUE TITLE
submit.rtbbase.org stopped working 

### ISSUE THREAD

**Issue by nmenda** [Planteome/Ontology-Variable-Request-App#35]
returns 'internal server error'

**Comment by nmenda** [comment]
here is the error from the server
 `Traceback (most recent call last):
  File "/home/production/submit.rtbbase.org/venv/lib/python3.6/site-packages/gevent/pywsgi.py", line 935, in handle_one_response
    self.run_application()
  File "/home/production/submit.rtbbase.org/venv/lib/python3.6/site-packages/gevent/pywsgi.py", line 908, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "/home/production/submit.rtbbase.org/venv/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/production/submit.rtbbase.org/venv/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/production/submit.rtbbase.org/venv/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/production/submit.rtbbase.org/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/production/submit.rtbbase.org/venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/production/submit.rtbbase.org/venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/production/submit.rtbbase.org/venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/production/submit.rtbbase.org/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/production/submit.rtbbase.org/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/production/submit.rtbbase.org/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/production/submit.rtbbase.org/request_handler.py", line 165, in oauth_receive
    issue_data, responsecode = make_issue(data,token)
  File "/home/production/submit.rtbbase.org/request_handler.py", line 66, in make_issue
    assign_and_label_issue(json.loads(r.content),data)
  File "/home/production/submit.rtbbase.org/request_handler.py", line 75, in assign_and_label_issue
    token = ah.installationToken(db.get_installation(data['onto-repo']))
  File "/home/production/submit.rtbbase.org/githubauthhandler.py", line 100, in installationToken
    raise Exception("{}:{}".format(r.status_code, r.content, ))
Exception: 401:b'{"message":"Bad credentials","documentation_url":"https://docs.github.com/rest"}'
Thu Feb 25 13:44:29 2021 {'REMOTE_ADDR': '::ffff:127.0.0.1', 'REMOTE_PORT': '40936', 'HTTP_HOST': 'localhost:5000', (hidden keys: 32)} failed with Exception

::ffff:127.0.0.1 - - [2021-02-25 13:44:29] "GET /authorized/oauth?code=de409b4cab31d89c4627&state=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJnb3RvIjoiaXNzdWUiLCJjYWNoZWRfYXMiOjM3LCJfX3JfXyI6IkFDMk5STFpBU1BaOUEzSFNQS01WTFNaVlc1ME5ZUjJJIn0.DBgVSO7qCAd3G4eKaVVGDtFbf1Je-n4PGVz5bPopkj8 HTTP/1.1" 500 161 1.014845
`

**Comment by cooperl09** [comment]
Message from GH:
Hello there!

On February 25th, 2021 at 15:38 (UTC) your application (Ontology Variable Submission App) used an access token (with the User-Agent python-requests/2.18.4) as part of a query parameter to access an endpoint through the GitHub API.

https://api.github.com/repositories/0/issues

Please use the Authorization HTTP header instead as using the `access_token` query parameter is deprecated.

Depending on your API usage, we'll be sending you this email reminder on a monthly basis.

Visit https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param for more information about suggested workarounds and removal dates.

Thanks,
The GitHub Team
